# Generated by Django 6.0.1 on 2026-02-12 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_play_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_ending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('next_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_choices', to='djangoapp.page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='djangoapp.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.story'),
        ),
    ]
