# Generated by Django 6.0.1 on 2026-02-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_story_author_story_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(default='published', max_length=20),
        ),
    ]
